import { StyleSheet } from "react-native";
import Cores from "@/style_global/styles";

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  safe: { flex: 1, backgroundColor: Cores.BG },
  container: {
    flex: 1,
    gap: 18,
    paddingHorizontal: 22,
    paddingTop: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Cores.BG,
  },
  brand: { alignItems: "center", gap: 8, marginBottom: 4 },
  logoCircle: {
    width: 68,
    height: 68,
    borderRadius: 999,
    backgroundColor: Cores.PRIMARY,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  logoText: { color: "#0a0f14", fontSize: 28, fontWeight: "800" },
  title: { color: Cores.TEXT, fontSize: 24, fontWeight: "700" },
  subtitle: { color: Cores.MUTED, fontSize: 14 },
  card: {
    width: "100%",
    gap: 14,
    backgroundColor: Cores.CARD,
    borderRadius: 14,
    padding: 18,
    borderWidth: 1,
    borderColor: "#22272e",
  },
  field: { gap: 6 },
  label: { color: Cores.TEXT, fontSize: 14, fontWeight: "600" },
  input: {
    height: 48,
    borderRadius: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#29313a",
    backgroundColor: "#0f141a",
    color: Cores.TEXT,
    fontSize: 16,
  },
  passwordRow: { flexDirection: "row", alignItems: "center" },
  inputPassword: { flex: 1, marginRight: 8 },
  showBtn: {
    height: 48,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#29313a",
    backgroundColor: "#0f141a",
  },
  showText: { color: Cores.PRIMARY, fontWeight: "600" },
  rowBetween: {
    marginTop: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rowCenter: { flexDirection: "row", alignItems: "center", gap: 8 },
  muted: { color: Cores.MUTED, fontSize: 14 },
  link: { color: Cores.PRIMARY, fontWeight: "700" },
  error: { color: Cores.ERROR, marginTop: 6 },
  btn: {
    height: 50,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Cores.PRIMARY,
    marginTop: 6,
  },
  btnText: { color: "#0a0f14", fontSize: 16, fontWeight: "800", letterSpacing: 0.3 },
  footerRow: {
    marginTop: 8,
    flexDirection: "row",
    gap: 6,
    justifyContent: "center",
  },
  footnote: { color: "#6b7280", fontSize: 12, marginTop: 8 },
});

export default styles;